font_family family="Iosevka Nerd Font"
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12

cursor                  #d3c6aa
cursor_text_color       background

url_color               #7fbbb3

visual_bell_color       #83c092
bell_border_color       #83c092

active_border_color     #a7c080
inactive_border_color   #414b50

foreground              #d3c6aa
background              #272e33
selection_foreground    #272e33
selection_background    #d3c6aa

active_tab_foreground   #272e33
active_tab_background   #a7c080
inactive_tab_foreground #d3c6aa
inactive_tab_background #272e33

# black  (bg3/bg4)
color0                  #414b50
color8                  #414b50

# red
color1                  #e67e80
color9                  #e67e80

#: green
color2                  #a7c080
color10                 #a7c080

# yellow
color3                  #dbbc7f
color11                 #dbbc7f

# blue
color4                  #7fbbb3
color12                 #7fbbb3

# purple
color5                  #d699b6
color13                 #d699b6

# aqua
color6                  #83c092
color14                 #83c092

# white (fg4/fg3)
color7                  #d3c6aa
color15                 #d3c6aa
