# Colors (Gruvbox Material Medium Dark)

# Default colors
[colors.primary]
background = '#14171d'
foreground = '#C5C9C7'

# Normal colors
[colors.normal]
black = '#14171d'
red = '#c4746e'
green = '#8a9a7b'
yellow = '#c4b28a'
blue = '#8ba4b0'
magenta = '#a292a3'
cyan = '#8ea4a2'
white = '#C5C9C7'

# Bright colors (same as normal colors)
[colors.bright]
black = '#14171d'
red = '#c4746e'
green = '#8a9a7b'
yellow = '#c4b28a'
blue = '#8ba4b0'
magenta = '#a292a3'
cyan = '#8ea4a2'
white = '#C5C9C7'
