# Colors (Gruvbox Material Medium Dark)

# Default colors
[colors.primary]
background = '#181818'
foreground = '#e4e4e4'

# Normal colors
[colors.normal]
black = '#282828'
red = '#f43841'
green = '#73d936'
yellow = '#ffdd33'
blue = '#96a6c8'
magenta = '#9e95c7'
cyan = '#95a99f'
white = '#e4e4e4'

# Bright colors (same as normal colors)
[colors.bright]
black = '#282828'
red = '#f43841'
green = '#73d936'
yellow = '#ffdd33'
blue = '#96a6c8'
magenta = '#9e95c7'
cyan = '#95a99f'
white = '#e4e4e4'

[font]
normal = { family="Iosevka Nerd Font" }
bold = { family="Iosevka Nerd Font" }
italic = { family="Iosevka Nerd Font" }
size = 11
offset.y = 1
