$background_color=rgba(191724ff)
$foreground_color=rgba(e0def4ff)
$green_color=rgba(9ccfd8ff)
$red_color=rgba(eb6f92ff)
$blue_color=rgba(31748fff)
$pink_color=rgba(ebbcbaff)
$primary_color=$pink_color
$secondary_color=$red_color

