[description]
id="catppuccin"
name="catppuccin"

[colors]
background = '#1E1E2E' # base
background_alt = '#32302f'
foreground = '#CDD6F4' # text
black = '#45475A' # surface1
red = '#F38BA8' # red
green = '#A6E3A1' # green
yellow = '#F9E2AF' # yellow
blue = '#89B4FA' # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5' # teal
white = '#BAC2DE' # subtext1
primary = "magenta"
