$background_color=rgb(272e33)
$foreground_color=rgb(d3c6aa)
$green_color=rgb(a7c080)
$red_color=rgb(e67e80)
$blue_color=rgb(7fbbb3)
$magenta_color=rgb(d699b6)
$yellow_color=rgb(dbbc7f)
$orange_color=rgb(E69875)
$primary_color=$green_color
$secondary_color=$cyan_color

$wallpaper_path=/home/alle/dotfiles/wallpaper/everforest/background_everforest.png

$font=Iosevka Nerd Font
