[description]
id="solarized"
name="Solarized"

[colors]
background = '#002b36'
background_alt = '#073642'
foreground = '#839496'
black   = '#073642'
red     = '#dc322f'
green   = '#859900'
yellow  = '#b58900'
blue    = '#268bd2'
magenta = '#d33682'
cyan    = '#2aa198'
white   = '#eee8d5'
primary = "blue"
