# Colors used
source = ~/.config/hypr/hyprland/colors.conf

# Monitors and monitor workspaces assignments
source = ~/.config/hypr/hyprland/monitors.conf

# Variables used
source = ~/.config/hypr/hyprland/variables.conf

# Keybindings
source = ~/.config/hypr/hyprland/binds.conf

# Stuff to execute at startup
source = ~/.config/hypr/hyprland/execs.conf

# Keyboard and mouse configuration
source = ~/.config/hypr/hyprland/peripherals.conf

# Styling and animations
source = ~/.config/hypr/hyprland/style.conf

# Windowrules
source = ~/.config/hypr/hyprland/windowrules.conf
