$background_color=rgb(1d2021)
$foreground_color=rgb(ebdbb2)
$green_color=rgb(98971a)
$red_color=rgb(cc241d)
$blue_color=rgb(458588)
$magenta_color=rgb(b16286)
$orange_color=rgb(d65d0e)
$primary_color=$orange_color
$secondary_color=$green_color
