hl.on('hyprland.start', function()
    hl.exec_cmd('waybar')
    hl.exec_cmd('hyprpaper')
    hl.exec_cmd('hypridle')
    hl.exec_cmd('swaync')
    hl.exec_cmd('systemctl --user start hyprpolkitagent')
    hl.exec_cmd('~/.config/hypr/hyprland/power-alert.py')
    hl.exec_cmd('kbuildsycoca6')
    hl.exec_cmd('gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps')
end)
