#exec-once = playerctld
exec-once = waybar
#exec-once = qs
exec-once = elephant
exec-once = hyprpaper
exec-once = swaync
exec-once = hypridle
exec-once = systemctl --user start hyprpolkitagent
exec-once = ~/.config/hypr/hyprland/power-alert.py
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
