monitor=,1920x1080,auto,1
#monitor=HDMI-A-2,1920x1080,0x0,1
monitor=eDP-1,1920x1080,1920x0,1
monitor=HDMI-A-2,1920x1080,0x0,1
#monitor=,1920x1080,auto,auto

workspace=1, monitor:HDMI-A-2
workspace=2, monitor:HDMI-A-2
workspace=3, monitor:HDMI-A-2
workspace=4, monitor:HDMI-A-2
workspace=5, monitor:HDMI-A-2
workspace=6, monitor:HDMI-A-2
workspace=7, monitor:HDMI-A-2
workspace=8, monitor:HDMI-A-2
workspace=9, monitor:eDP-1
workspace=10, monitor:eDP-1
