# Super key
$mainMod = SUPER

$terminal = alacritty -e tmux
$fileManager = nautilus
$menu = ~/.config/rofi/scripts/launcher.sh
$poweroffMenu = ~/.config/rofi/scripts/powermenu.sh

# environment vars.
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt6ct # change to qt6ct if you have that
env = GTK_THEME,Adwaita:dark
