# Super key
$mainMod = SUPER

$terminal = ghostty -e tmux
$fileManager = dolphin
$menu = ~/.config/rofi/scripts/launcher.sh
$poweroffMenu = ~/.config/rofi/scripts/powermenu.sh

# environment vars.
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,kde # change to qt6ct if you have that
env = XDG_MENU_PREFIX,arch-
