windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Used for popups
windowrule = float on, match:class ^$
windowrule = float on, match:class ^Firefox$
windowrule = float on, match:class .*, match:title ^rviz2$
windowrule = float on, match:class .*, match:title ^win([0-9])*$
windowrule = float on, match:class .*, match:title ^Choose Content to Paste$
windowrule = float on, match:class steam, match:title ^$
windowrule = float on, match:class .*, match:title ^(.*Menu.*)$
windowrule = no_focus on, match:class ^(gtk)$, match:title ^(popup)$

# Personalized rules
windowrule = float on, center on, size 800 600, match:class ^(.*pavucontrol.*)$
windowrule = float on, center on, size 800 600, match:class ^.*tui$

# Workspace assignments
windowrule = workspace 1, match:class kitty
windowrule = workspace 1, match:class com.mitchellh.ghostty
windowrule = workspace 2, match:class firefox
windowrule = workspace 2, match:class zen
windowrule = workspace 3, match:class BambuStudio
windowrule = workspace 9, match:class rviz2
windowrule = workspace 10, match:class spotify

layerrule = no_anim on, match:namespace selection
