[description]
id="rosepine"
name="Rosepine"

[colors]
background = '#191724'
background_alt = '#6e6a86'
foreground = '#e0def4'
black = '#26233a'
red = '#eb6f92'
green = '#31748f'
yellow = '#f6c177'
blue = '#9ccfd8'
magenta = '#c4a7e7'
cyan = '#ebbcba'
white = '#e0def4'
primary = "magenta"
