#+TITLE:GNU Emacs config
#+STARTUP: showeverything
#+OPTIONS: toc:2

* TABLE OF CONTENTS :toc:
- [[#backup][BACKUP]]
- [[#load-scripts-folder][LOAD SCRIPTS FOLDER]]
- [[#elpaca][ELPACA]]
- [[#evil][EVIL]]
- [[#general-keybindings][GENERAL KEYBINDINGS]]
- [[#company][COMPANY]]
- [[#dired][DIRED]]
- [[#dashboard][DASHBOARD]]
- [[#diminish][DIMINISH]]
- [[#flycheck][FLYCHECK]]
- [[#icons][ICONS]]
- [[#fonts][FONTS]]
- [[#graphical-user-interface-tweaks][GRAPHICAL USER INTERFACE TWEAKS]]
- [[#ivy][IVY]]
- [[#language-support][LANGUAGE SUPPORT]]
- [[#modeline][MODELINE]]
- [[#neotree][NEOTREE]]
- [[#org-mode][ORG MODE]]
- [[#projectile][PROJECTILE]]
- [[#rainbow-mode][RAINBOW MODE]]
- [[#reload-emacs][RELOAD EMACS]]
- [[#shells-and-terminals][SHELLS AND TERMINALS]]
- [[#theme][THEME]]
- [[#which-key][WHICH-KEY]]

* BACKUP
#+begin_src emacs-lisp
(setq backup-directory-alist '((".*" . "~/.config/emacs/.Trash")))
#+end_src

* LOAD SCRIPTS FOLDER
#+begin_src emacs-lisp
(add-to-list 'load-path "~/.config/emacs/scripts/")
#+end_src

* ELPACA
Elpaca is an elisp package manager. It allows users to find, install, update, and remove third-party packages for Emacs.
It is a replacement for the built-in Emacs package manager, package.el.
#+begin_src emacs-lisp
(require 'elpaca-setup)
#+end_src

* EVIL
Evil is an extensible vi layer for Emacs. It emulates the main features of Vim, and provides facilities for writing custom extensions. 
#+begin_src emacs-lisp
(require 'evil-setup)
#+end_src

* GENERAL KEYBINDINGS
More convenient key definitions in emacs 
#+begin_src emacs-lisp
(require 'general-keybindings-setup)
#+end_src

* COMPANY
Company is a text completion framework for Emacs. The name stands for “complete anything”.  Completion will start automatically after you type a few letters. Use M-n and M-p to select, <return> to complete or <tab> to complete the common part.
#+begin_src emacs-lisp
(require 'company-setup)
#+end_src

* DIRED
#+begin_src emacs-lisp
(require 'dired-setup)
#+end_src

* DASHBOARD
Emacs Dashboard is an extensible startup screen showing you recent files, bookmarks, agenda items and an Emacs banner.

#+begin_src emacs-lisp
(require 'dashboard-setup)
#+end_src

* DIMINISH
#+begin_src emacs-lisp
(use-package diminish)
#+end_src

* FLYCHECK
#+begin_src emacs-lisp
(require 'flycheck-setup)
#+end_src

* ICONS
#+begin_src emacs-lisp
(require 'icons-setup)
#+end_src


* FONTS
Defining the various fonts that Emacs will use.

#+begin_src emacs-lisp
(require 'fonts-settings)
#+end_src


* GRAPHICAL USER INTERFACE TWEAKS
Let's make GNU Emacs look a little better.

#+begin_src emacs-lisp
(require 'ui-settings)
#+end_src

* IVY
+ Ivy, a generic completion mechanism for Emacs.
+ Counsel, a collection of Ivy-enhanced versions of common Emacs commands.
+ Ivy-rich allows us to add descriptions alongside the commands in M-x.

#+begin_src emacs-lisp
(require 'ivy-setup)
#+end_src

* LANGUAGE SUPPORT
#+begin_src emacs-lisp
(require 'language-support)
#+end_src

* MODELINE
#+begin_src emacs-lisp
(require 'modeline-setup)
#+end_src

* NEOTREE
#+begin_src emacs-lisp 
(require 'neotree-setup)
#+end_src

* ORG MODE
#+begin_src emacs-lisp
(require 'orgmode-setup)
#+end_src
* PROJECTILE
#+begin_src emacs-lisp
(require 'projectile-setup)
#+end_src

* RAINBOW MODE
#+begin_src emacs-lisp
(require 'rainbowmode-setup.el)
#+end_src

* RELOAD EMACS
#+begin_src emacs-lisp
  (defun reload-init-file ()
    (interactive)
    (load-file "~/.config/emacs/init.el")
    (load-file "~/.config/emacs/init.el"))
#+end_src

* SHELLS AND TERMINALS
#+begin_src emacs-lisp
(require 'terminal-setup)
#+end_src

* THEME
#+begin_src emacs-lisp
(require 'theme-setup.el)
#+end_src

* WHICH-KEY
#+begin_src emacs-lisp
(require 'which-key-setup.el)
#+end_src

