[description]
id="thorn"
name="thorn"

[colors]
background = '#172526'
background_alt = '#568270'
foreground = '#DBD2C7'
black = '#172526'
red = '#D2696C'
green = '#88B497'
yellow = '#FFD7AA'
blue = '#91C4C0'
magenta = '#F9ADA0'
cyan = '#87CBB1'
white = '#A1A790'
primary = "green"
