background_color = "#1d2021"
foreground_color = "#ebdbb2"
background_alt_color = "#504945"
black_color     = "#282828"
red_color       = "#cc241d"
green_color     = "#98971a"
yellow_color    = "#d79921"
blue_color      = "#458588"
magenta_color   = "#b16286"
cyan_color      = "#689d6a"
orange_color    = "#d65d0e"
white_color     = "#ebdbb2"

primary_color_name = "orange"
secondary_color_name = "green"

neovim_theme_repo = "https://github.com/ellisonleao/gruvbox.nvim"
neovim_theme_opts = [
    'require("gruvbox").setup({contrast="hard"})',
]
neovim_theme_name = "gruvbox"
