background_color     = "#14171d"
foreground_color     = "#C5C9C7"
background_alt_color = "#393B44"
black_color          = "#14171d"
red_color            = "#c4746e"
green_color          = "#8a9a7b"
yellow_color         = "#c4b28a"
blue_color           = "#8ba4b0"
magenta_color        = "#a292a3"
cyan_color           = "#8ea4a2"
white_color          = "#C5C9C7"
orange_color         = "#b6927b"

primary_color_name = "blue"
secondary_color_name = "white"

neovim_theme_repo = "https://github.com/webhooked/kanso.nvim"
neovim_theme_opts = [
    "require('kanso').setup({background = {dark = 'ink'}})"
]
neovim_theme_name = "kanso"
