$background_color=rgb(002b36)
$foreground_color=rgb(839496)
$green_color=rgb(859900)
$red_color=rgb(dc322f)
$blue_color=rgb(268bd2)
$magenta_color=rgb(d33682)
$primary_color=$blue_color
$secondary_color=$green_color

