$background_color=rgb(161617)
$foreground_color=rgb(c9c7cd)
$black_color   = rgb(27272a)
$red_color     = rgb(ea83a5)
$green_color   = rgb(90b99f)
$yellow_color  = rgb(e6b99d)
$blue_color    = rgb(9ca2cf)
$magenta_color = rgb(e29eca)
$cyan_color    = rgb(85b5ba)
$white_color   = rgb(c9c7cd)
$primary_color=$blue_color
$secondary_color=$red_color

