include theme.conf

fontfamily JetbrainsMono Nerd Font
font_size 11.0

cursor_shape beam

auto_reload_config 0.1
term xterm-256color

startup_session ~/.config/kitty/sessions/default.kitty-session

confirm_os_window_close 0

tab_bar_edge top
tab_bar_min_tabs 1
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template {session_name}: {index} {title}
tab_title_max_length 20
tab_bar_filter session:~ or session:^$

enabled_layouts splits,stack

map ctrl+shift+e launch --location=vsplit --cwd=current 
map ctrl+shift+o launch --location=hsplit --cwd=current 
map ctrl+shift+z combine : toggle_layout stack : move_window_to_top
map ctrl+shift+t launch --type=tab --cwd=current

map ctrl+shift+1 goto_tab 1
map ctrl+shift+2 goto_tab 2
map ctrl+shift+3 goto_tab 3
map ctrl+shift+4 goto_tab 4
map ctrl+shift+5 goto_tab 5
map ctrl+shift+6 goto_tab 6
map ctrl+shift+7 goto_tab 7
map ctrl+shift+8 goto_tab 8
map ctrl+shift+9 goto_tab 9
map ctrl+shift+10 goto_tab 10

map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window down

map ctrl+shift+s goto_session ~/.config/kitty/sessions/default.kitty-session
map ctrl+shift+f goto_session ~/.config/kitty/sessions
map ctrl+shift+n save_as_session --save-only=yes --use-foreground-process=yes ~/.config/kitty/sessions/created.kitty_session
