font_family family="Iosevka Nerd Font"
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12

cursor                  #C5C9C7
cursor_text_color       background

url_color               #8ba4b0

visual_bell_color       #8ea4a2
bell_border_color       #8ea4a2

active_border_color     #8ba4b0
inactive_border_color   #14171d

foreground              #C5C9C7
background              #14171d
selection_foreground    #14171d
selection_background    #C5C9C7

active_tab_foreground   #14171d
active_tab_background   #8ba4b0
inactive_tab_foreground #C5C9C7
inactive_tab_background #14171d

# black  (bg3/bg4)
color0                  #14171d
color8                  #14171d

# red
color1                  #c4746e
color9                  #c4746e

#: green
color2                  #8a9a7b
color10                 #8a9a7b

# yellow
color3                  #c4b28a
color11                 #c4b28a

# blue
color4                  #8ba4b0
color12                 #8ba4b0

# purple
color5                  #a292a3
color13                 #a292a3

# aqua
color6                  #8ea4a2
color14                 #8ea4a2

# white (fg4/fg3)
color7                  #C5C9C7
color15                 #C5C9C7
