# Based on https://github.com/morhetz/gruvbox by morhetz <morhetz@gmail.com>
# Adapted to kitty by wdomitrz <witekdomitrz@gmail.com>

cursor                  #ebdbb2
cursor_text_color       background

url_color               #458588

visual_bell_color       #689d6a
bell_border_color       #689d6a

active_border_color     #d65d0e
inactive_border_color   #282828

foreground              #ebdbb2
background              #1d2021
selection_foreground    #1d2021
selection_background    #ebdbb2

active_tab_foreground   #1d2021
active_tab_background   #d65d0e
inactive_tab_foreground #ebdbb2
inactive_tab_background #1d2021

# black  (bg3/bg4)
color0                  #282828
color8                  #282828

# red
color1                  #cc241d
color9                  #cc241d

#: green
color2                  #98971a
color10                 #98971a

# yellow
color3                  #d79921
color11                 #d79921

# blue
color4                  #458588
color12                 #458588

# purple
color5                  #b16286
color13                 #b16286

# aqua
color6                  #689d6a
color14                 #689d6a

# white (fg4/fg3)
color7                  #ebdbb2
color15                 #ebdbb2
