set $background_color #141415
set $background_alt_color #252530
set $foreground_color #cdcdcd
set $black_color #252530
set $green_color #7fa563
set $red_color #d8647e
set $blue_color #6e94b2
set $cyan_color #aeaed1
set $magenta_color #bb9dbd
set $yellow_color #f3be7c
set $orange_color #f3be7c
set $white_color #cdcdcd
set $primary_color $cyan_color
set $secondary_color $blue_color

set $wallpaper_path "/home/alle/dotfiles/wallpaper/vague/background_vague.png"

set $font "Iosevka Nerd Font"
