set $background_color #1d2021
set $background_alt_color #504945
set $foreground_color #ebdbb2
set $green_color #98971a
set $red_color #cc241d
set $blue_color #458588
set $magenta_color #b16286
set $yellow_color #d79921
set $orange_color #d65d0e
set $primary_color $orange_color
set $secondary_color $green_color

set $wallpaper_path "/home/alle/dotfiles/wallpaper/gruvbox/background_gruvbox.png"

set $font "Iosevka Nerd Font"
