set $background_color #191724
set $background_alt_color #1f1d2e
set $foreground_color #e0def4
set $black_color #26233a
set $green_color #31748f
set $red_color #eb6f92
set $blue_color #9ccfd8
set $magenta_color #c4a7e7
set $yellow_color #f6c177
set $orange_color #ebbcba
set $white_color #e0def4
set $primary_color $magenta_color
set $secondary_color $blue_color

set $wallpaper_path "/home/alle/dotfiles/wallpaper/rosepine/background_rosepine.jpg"

set $font "Iosevka Nerd Font"
