for_window [app_id="kitty"] exec swaymsg 'move container to workspace number 1; workspace number 1'
for_window [app_id="Alacritty"] exec swaymsg 'move container to workspace number 1; workspace number 1'
for_window [app_id="com.mitchellh.ghostty"] exec swaymsg 'move container to workspace number 1; workspace number 1'
for_window [app_id="foot"] exec swaymsg 'move container to workspace number 1; workspace number 1'

for_window [app_id="zen"] exec swaymsg 'move container to workspace number 2; workspace number 2'
for_window [app_id="librewolf"] exec swaymsg 'move container to workspace number 2; workspace number 2'
for_window [app_id="firefox"] exec swaymsg 'move container to workspace number 2; workspace number 2'
for_window [app_id="qutebrowser"] exec swaymsg 'move container to workspace number 2; workspace number 2'
for_window [app_id="helium"] exec swaymsg 'move container to workspace number 2; workspace number 2'

for_window [class="BambuStudio"] exec swaymsg 'move container to workspace number 3; workspace number 3'
for_window [app_id="orca-slicer"] exec swaymsg 'move container to workspace number 3; workspace number 3'
for_window [app_id="jetbrains-studio"] exec swaymsg 'move container to workspace number 3; workspace number 3'

for_window [app_id="org.telegram.desktop"] exec swaymsg 'move container to workspace number 4; workspace number 4'

for_window [app_id="org.polymc.PolyMC"] exec swaymsg 'move container to workspace number 5; workspace number 5'
for_window [class="Minecraft*"] exec swaymsg 'move container to workspace number 5; workspace number 5'

for_window [class="rviz2"] exec swaymsg 'move container to workspace number 9; workspace number 9'

for_window [class="Spotify"] exec swaymsg 'move container to workspace number 10; workspace number 10'
