assign [app_id="kitty"] workspace number 1
assign [app_id="Alacritty"] workspace number 1
assign [app_id="com.mitchellh.ghostty"] workspace number 1
assign [app_id="foot"] workspace number 1
assign [app_id="jetbrains-studio"] workspace number 1

assign [app_id="zen"] workspace number 2
assign [app_id="librewolf"] workspace number 2
assign [app_id="firefox"] workspace number 2
assign [app_id="qutebrowser"] workspace number 2
assign [app_id="helium"] workspace number 2

assign [class="BambuStudio"] workspace number 3
assign [app_id="orca-slicer"] workspace number 3

assign [app_id="org.telegram.desktop"] workspace number 4

assign [app_id="org.polymc.PolyMC"] workspace number 5
assign [class="Minecraft*"] workspace number 5

assign [class="rviz2"] workspace number 9

assign [class="Spotify"] number 10

for_window [app_id=".*tui"] floating enable
for_window [app_id="org.pulseaudio.pavucontrol"] floating enable
